# docker-compose.yml
---
version: '2'
services:

  app:
    image: webdevops/php:alpine-php7
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./wp:/var/www/html/

  web:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app
    depends_on:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST=wp-bedrock.docker
      - VIRTUAL_PORT=80

  yarn:
    image: node:alpine
    links:
      - web:wp-bedrock.docker
    depends_on:
      - app
      - web
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST=sync.wp-bedrock.docker
      - VIRTUAL_PORT=3000
    entrypoint: /bin/sh

  db:
    image: mariadb
#    volumes:
#      - ./.docker/db:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=password

  memcached:
    image: memcached:alpine
